### ISSUE TITLE
Beaker complains about host unreachable - Ubuntu 18 and 20

### ISSUE THREAD

**Issue by lpossamai** [voxpupuli/beaker-docker#39]
When executing the command `bundle exec rake beaker:ubuntu-1804-docker`, Beaker displays the following error:

`Beaker::Hypervisor, found some docker boxes to createProvisioning dockerprovisioning example-node.exampleUsing container connection at 172.17.0.83:22  Warning: Try 1 -- Host 172.17.0.83 unreachable: Errno::ECONNREFUSED - Connection refused - connect(2) for 172.17.0.83:22  Warning: Trying again in 3 seconds  Warning: Try 2 -- Host 172.17.0.83 unreachable: Errno::ECONNREFUSED - Connection refused - connect(2) for 172.17.0.83:22  Warning: Trying again in 5 seconds`

This issue is only happening for Ubuntu 18 (`beaker:ubuntu-1804-docker`) and 20 (`beaker:ubuntu-2004-docker`), for Ubuntu 14 and 16, it's working.

`ubuntu-1804-docker.yml node-set`:

```
HOSTS:
  example-node.example:
    platform: ubuntu-18.04-amd64
    image: ubuntu:18.04
    hypervisor: docker
    docker_preserve_image: false
    docker_cmd: '["/sbin/init"]'
    docker_image_commands:
      - 'apt-get install -y net-tools wget curl locales apt-transport-https software-properties-common iptables'
      - 'locale-gen en_US.UTF-8'
CONFIG:
  type: aio
  puppet_collection: puppet6
  puppet_agent_version: 6.17.0
```

Any help would be much appreciated, please.
Thanks!
